### ISSUE TITLE
target frame position resets

### ISSUE THREAD

**Issue by Ladish** [MizukiBelhi/ExtendedUI#1]
Target frame position resets to default if ExtendedUI setting window is closed. It goes back to set position once the setting window is opened again.

**Comment by MizukiBelhi** [comment]
I can't replicate this.. seems to work fine for me. Are you sure you pressed save before closing the window?

**Comment by Ladish** [comment]
Yes I did.

[TOS 2016-05-26 10-33-53-807.zip](https://github.com/MizukiBelhi/ExtendedUI/files/284607/TOS.2016-05-26.10-33-53-807.zip)

**Comment by MizukiBelhi** [comment]
Thanks! Seems like targetinfo resets itself everytime it receives info about a mob. Let's hope when i fix it there won't be any incompatibilities with monsterframes.

**Comment by bsides** [comment]
If you need any help fixing this let me know. Right now if you open the Extended UI interface it puts it back to its place so I guess there is a call on default reset method that should include your settings.

**Comment by roflmbo** [comment]
I'm having the exact same problem.

I made a thread about it in the wrong place. But you can look at the details again if you want.
https://github.com/Excrulon/Tree-of-Savior-Addon-Manager/issues/7
