### ISSUE TITLE
Quick-keys in front of menus

### ISSUE THREAD

**Issue by BarUtJeh** [MizukiBelhi/ExtendedUI#10]
First of all, love the addon. It lets me make more efficient use of my smaller screen, especially when using mouse controls.

One thing is that I've moved my quick-keys to the side. The problem with that is, that when I open any menu on the right side, the quick-keys are displayed over it, making it hard to use the bottom part of the screen.

It could be an option, though I can't imagine anyone not wanting the menus to always be on top.

Regards,

Bart

**Comment by MizukiBelhi** [comment]
I'll look into it, don't get your hopes up though.
