### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by s1lv3rw0lf** [MizukiBelhi/ExtendedUI#12]
1. An option to return the UI element individually to its default location.

https://i.imgur.com/lfr18bI.png

2. The ability to extend the buff/debuff slot on target buff UI similar to our own buff/debuff slot.

https://i.imgur.com/xr7t0Mx.png

**Comment by MizukiBelhi** [comment]
ExtendedBuff will not be added for targetbuff, sorry!
