### ISSUE TITLE
Characters with different Input Types

### ISSUE THREAD

**Issue by LightDarkSide** [MizukiBelhi/ExtendedUI#14]
Hello,

I ran into a small issue with ExtendedUI.
With this Addon installed the input mode carries over after character switch.
E.g. if I'm using Mouse Mode on Char1 and switch to Char2 with keyboard mode selected Char2 will use Mouse Mode (even though in settings it has keyboard mode). Same for the reverse situation (Keyboard to Mouse).

Regards

**Comment by MizukiBelhi** [comment]
Are you sure this is related to EUI? EUI doesn't touch any control or game settings.

**Comment by LightDarkSide** [comment]
It's the only Addon I installed earlier and the issue stopped right after uninstalling it again. I need to check later if it's caused by combining it with a different addon.

**Comment by MizukiBelhi** [comment]
We're (or rather wolfy) is currently investigating the issue.

**Comment by LightDarkSide** [comment]
Hm, I don't know if I installed too many addons and my game broke at some point but the problem still persists after moving all other addons out of the data folder and removing the old settings.

**Comment by s1lv3rw0lf** [comment]
I tested it. It only happens when installing EUI. 

Misuki pushed a fix for the next version~

**Comment by MizukiBelhi** [comment]
We'll see if https://github.com/MizukiBelhi/ExtendedUI/commit/0cfd286166d16c861fb12a48b57360e3184f76e0 fixes the issue. Will test later tonight and then push an update.

**Comment by MizukiBelhi** [comment]
Just tested it, it's not fixed yet.
