### ISSUE TITLE
trouble display the menu icon on new update

### ISSUE THREAD

**Issue by felicoz** [MizukiBelhi/ExtendedUI#16]
hi i am in taiwanese server so it's probably different.

i have trouble displaying the extended ui icon on the menu after update, and every time i switch the character the system would print error like "ShowWindow' argument #3 boolean expected

Cheers

**Comment by MizukiBelhi** [comment]
A screenshot of the error and more information on how you have trouble displaying the icon would help greatly. 

This might actually be an issue with acutil, try reinstalling EUI through the addon manager?

**Comment by felicoz** [comment]
screenshot,
http://ohn525cfa.bkt.clouddn.com/11111.png

**Comment by MizukiBelhi** [comment]
acutil has been fixed. Reinstall a random addon from the manager to update.

**Comment by felicoz** [comment]
thanks！
