### ISSUE TITLE
Spells change color

### ISSUE THREAD

**Issue by NeoZeromus** [MizukiBelhi/ExtendedUI#2]
Well after installing this addon i noticed my elementalist spells all turn blackish color when hitting some of the container boxes, this happens with magic missile, hail and sometimes with meteor

![screenshot_20160518_00007](https://cloud.githubusercontent.com/assets/3309166/15359257/bae9352a-1cc5-11e6-8e16-632d9a295e34.jpg)

**Comment by MizukiBelhi** [comment]
Are you sure this is related to EUI? Have you removed EUI and seen if the problem persists?
