### ISSUE TITLE
Mini Map resizing

### ISSUE THREAD

**Issue by Nangl** [MizukiBelhi/ExtendedUI#26]
Hi, I'm not sure if this is a known issue or not. Since I couldn't find anything about it im assuming it's not.
After the most recent ToS maintenance (November 6th, 2018), sometimes when I load into a new zone, the mini map auto resizes to a very small window.

(As you can see in the screenshot I do have another minimap related addon, but I've tried disabling any other UI related addons, and the problem persists)
![minimap](https://user-images.githubusercontent.com/44829514/48115337-b8758680-e249-11e8-82ea-dd9481551894.png)

Really loving this addon, hope you're still keeping it update. 
Thank you!

**Comment by MizukiBelhi** [comment]
I'm not sure if EUI is the cause of this. Resizing the minimap is disabled (it's not touching the values) and EUI seems to load AFTER the minimap resizes.

**Comment by Nangl** [comment]
I'm so sorry to bother you with this. Aparently it was a client bug and IMC fixed.
A friend confirmed that he was having this issue and he doesn't use ExtendedUI

Thank you for taking the time to check and respond though!
