### ISSUE TITLE
Resizing feature

### ISSUE THREAD

**Issue by Romsh** [MizukiBelhi/ExtendedUI#27]
Hi. Sorry if you told already how to do or when but it seems that i can't find how to resize the UI like keyboard quickslot or player health for example.

I just came from a Reddit post which you told adding the feature soon. Perhaps a date if you will add it ?

Thanks for your work anyway :)

**Comment by MizukiBelhi** [comment]
It's in there, a lot of them have it disabled though because it's very time intensive to make a special case for every UI element. Resizing them is a pain.
