### ISSUE TITLE
Issues with chat.

### ISSUE THREAD

**Issue by Koraxor** [MizukiBelhi/ExtendedUI#35]
With extendedui on I have an issue where my chat box will stop updating until I disable/renable one of the filters (system message, combat messages etc) then it will update as I receive messages again for a little while. I generally only notice when the shouts are scrolling on the top of the screen but the chat box isn't displaying them, and then I realize I've been missing like 30 minutes of guild messages once I disable a filter.

I have not attempted to disable every addon yet, but I have tried disabling any addon that affects the chat box that I know of.

**Comment by MizukiBelhi** [comment]
EUI 2.1.0 has the chat removed, therefore it does not affect it.
