### ISSUE TITLE
Merc Shop Button and Resetting UI causes a bunch of misplacement.

### ISSUE THREAD

**Issue by Kohtas** [MizukiBelhi/ExtendedUI#40]
Hello, having the same issue as someone else here where the merc shop button is either visible or hidden 100% and separates itself from the shop popout menu.

Also noticed that resetting everything to default causes a bunch of things to go out of whack, for example the XP bar ends up in the middle of the screen, buffs end up overlapping, etc. I'd recreated it for a screenshot however I'm not going to spend 45minutes setting everything back up manually.

Only issues I've noticed so far. Thanks for the addon otherwise, it's a huge improvement.

**Comment by Kohtas** [comment]
Now it's gone completely unless I open up the UI editor to show it again but then it's temporary. Also noticing a few different issues now as well, this addon should be marked as out dated.

**Comment by MizukiBelhi** [comment]
Use the "always update" option under the advanced frame settings if there are issues with certain UI elements.
Reset doesn't support child frames, which is why the buffs go all over the place, XP bar being misplaced is however a bug.
If there are other issues please list them properly.

**Comment by Kohtas** [comment]
"Always update" does nothing for the Merc Shop button, and I'm not sure how you'd like me to list the issues, you've provided no format you'd like used so I listed them under the "issues" tab. The addon is great, however it is a complete mess to be honest. Not trying to be rude by any means, if you have a specific format you'd like the issues listed in I'd be happy to make a proper list for you, however it will be long.

**Comment by Kohtas** [comment]
Sorry, correction. I must have missed the "Issues" section on the main page, however you did say "Alternatively, please open up an issue." which I did and would do rather than talk in game that way issues are seen on the page and not left to private messages.

**Comment by MizukiBelhi** [comment]
https://user-images.githubusercontent.com/19305926/143677332-efae4575-fd51-49e5-90d5-c3ad3960eb64.mp4

Honestly, I have no idea what you mean by it "separates itself from the shop popout menu". It's a button it's not attached to anything? See video, it works fine for me.

For other issues, just list them and how to reproduce them easily.

**Comment by Kohtas** [comment]
![image](https://user-images.githubusercontent.com/68921186/143677473-c0c6c804-b125-4313-8eac-9dc8a7f5f1bc.png)

When EUI is installed, it pops the button out from the popout menu regardless of you moving it yourself or not. And then when it's selected to "Always Update" it hides itself regardless of it's position. No reproduction needed for it, it just is like that for me. 

I can live without the addon personally though, I was only planning to use it in order to hide some annoyances (TP bottons, etc) that I've since just gotten used to. I do appreciate you creating the addon though and your time, I just CBA to deal with the little issues it has.

**Comment by MizukiBelhi** [comment]
I didn't even know that little menu existed. Then the button shouldn't even be an option to move.

**Comment by MizukiBelhi** [comment]
Sadly i can't fix bugs that i don't know about, and basically nobody tells me about issues so they remain unfixed.
[Hotfix for Merc Button](https://ci.appveyor.com/api/buildjobs/c3acdw6e8bt3u47d/artifacts/extendedui.ipf)
