### ISSUE TITLE
Merc Shop Button Gone

### ISSUE THREAD

**Issue by Kohtas** [MizukiBelhi/ExtendedUI#41]
Hey, I appreciate you taking the time to try to fix the Merc Shop button issue. However it's completely missing not, it's meant to be within the popout on the new shop button.

How it should look normally:
![image](https://user-images.githubusercontent.com/68921186/145189930-3d49d4d5-f6ad-4039-96d1-0098a89e5dfa.png)

When popped out (shop button clicked):
![image](https://user-images.githubusercontent.com/68921186/145189713-2774ba2d-d283-4fd4-8cc4-55c2fce87050.png)

The issue we had before is that it was floating independently of the popout menu and hiding and showing itself when it felt like it.

Is there a way to enable it again and just leave it attached to the new shop button?

**Comment by Kohtas** [comment]
Sorry, this is how it's supposed to look when clicked: 
![image](https://user-images.githubusercontent.com/68921186/145190507-cd04e58d-da4a-4390-87c2-597081dc8124.png)

The second image shared above is with EUI active.

**Comment by MizukiBelhi** [comment]
Have you tried the latest appveyor build [here](https://ci.appveyor.com/api/buildjobs/c3acdw6e8bt3u47d/artifacts/extendedui.ipf)? The update is _not_ available on the manager yet. If you **are** using the linked version, let me know, then it'll require a bigger fix (eui still modifying ui elements when they have been removed).

**Comment by Kohtas** [comment]
Oh gotcha, yea that's probably my problem then thank you. I'll install the newer build. I installed from the manager.

**Comment by Kohtas** [comment]
So I have no idea how to actually use that file you shared, is there a delay in updating it on the addon manager? I'm not sure how any of that works. It's not a big deal if I have to wait in order to use the new version of the addon, the merc shop button is still functional just not where it should be.

**Comment by MizukiBelhi** [comment]
I pushed the update to the manager for your convenience.

**Comment by Kohtas** [comment]
Thank you, appreciate it.
